### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#132]
[strings_fr.xml.zip](https://github.com/doerfli/hacked/files/4396139/strings_fr.xml.zip)

**Comment by Ilithy** [comment]
Hi, It's Nathanaël :relaxed:

Let me provide you here the XML files of the translation of :
[Hacked ? privacy policy](https://www.sendspace.com/file/pf091k)
[Presentation of Hacked ? on the Google Play Store.](https://www.sendspace.com/file/edsk3c)
_Files hosted on sendspace_ 

If this is not necessary, please ignore it.

See you later

Yours sincerely

**Comment by yoobi** [comment]
Hi what needs to be done here for the translation ? I'd like to be assigned for the issue

**Comment by doerfli** [comment]
Hi! 
I have not had time to verify the translation. And it looks like the link is no longer valid.
If you want to provide a new translation, you are welcome to do so.do you know your way around android apps or shall I link you the english string resource file?
Cheers, Marc

**Comment by yoobi** [comment]
Yeah, I've taken a look at the translation and there were some typos, I'm fine with android apps thank you :)

**Comment by doerfli** [comment]
Just open a pull request when you're done. Thank you!

**Comment by yoobi** [comment]
I've made PR https://github.com/doerfli/hacked/pull/141

**Comment by doerfli** [comment]
Just got it. Thanks. Ill see if i fine some time to validate it and then bring it online with the next app release.
