### ISSUE TITLE
Use inapp review api

### ISSUE THREAD

**Issue by doerfli** [doerfli/hacked#139]
https://developer.android.com/guide/playcore/in-app-review
use in `RatingHelper`

**Comment by erwinkaaa** [comment]
Hi! I'm new to open source. I would like to try to contribute to this!

**Comment by doerfli** [comment]
Welcome @erwinkaaa 
You can just implement this and create a pull request for me. Have you used the new review api already (I didn't 😬)?
Have a look at the current implementation in the class mentioned above. I think it should be clear where to call the new in-app api instead of redirecting to market. 
Let me know if you need more information about it. 
Cheers, Marc

**Comment by erwinkaaa** [comment]
Is it okay if i do the PR within hacktoberfest?

**Comment by doerfli** [comment]
Sure thing.

**Comment by malhotramanik** [comment]
Hello @doerfli 
I am new here. I want to contribute to this, may I?

**Comment by doerfli** [comment]
Since afaik there hasn't been any work done, you can give it a try. Just send me a PR for the change.
